apiVersion: v1
kind: Service
metadata:
  name: brain-tumor-classification
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: brain-tumor-classification
  ports:
    - port: 80 
      targetPort: 9696